# Generated by Django 3.1.7 on 2021-04-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210407_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='date',
            new_name='data',
        ),
    ]
